[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
TOV = "62bc0511-a336-4cf7-b18b-06a406332e14"

[compat]
CairoMakie = "0.15.8"
Documenter = "1"
